config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :videos
  get 'home/index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    include Visible
    has_many :comments, dependent: :destroy
    has_and_belongs_to_many :keywords
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
end

# def method(arg1, arg2, hash1, hash2)
# end

# method 1, 2, { a: 2 }, { b: 4 }


# def method2(arg1, arg2, hash)
# end

# method2 1, 2, a: 2, b: 4
# method2 1, 2, {a: 2, b: 4 }


# def comments
#     Comment.where(article_id: self.id)
#     => 'SELECT * FROM comments WHERE article_id = 3'
# end

# def has_many(arg1, options = {})
#     if options[:dependent] == :destroy
#         comments.destroy_all
#     elsif options[:dependent] == :nullify
#         comments.update_all(article_id: nil)
#     end
# end

# Gemfile
# --------
# gem 'devise'

app/models/comment.rb
class Comment < ApplicationRecord
  # include Visible
  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern
  
    VALID_STATUSES = ['public', 'private', 'archived']
  
    included do
      validates :status, inclusion: { in: VALID_STATUSES }
    end

    class_methods do
        def public_count
          where(status: 'public').count
        end
    end
  
    def archived?
      status == 'archived'
    end
end

app/models/keyword.rb
class Keyword < ApplicationRecord
    has_and_belongs_to_many :articles
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: {nonadmin: 0, admin: 1}
end

app/models/video.rb
class Video < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
  # Form with checkboxes
  # => params { title: 'h', body: 'b', status: 'public', keyword_ids: [1, 3, 4] }
  # article.update(params)
  # => article.title = 'h', article.body = 'b', article.status = 'public', article.keyword_ids = [1, 3, 4]
    def article_params
      params.require(:article).permit(:title, :body, :status, { keyword_ids: [] })
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    # http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
    def create
        # binding.pry
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article), status: 303
    end
    
    private
        def comment_params
            params.require(:comment).permit(:commenter, :body, :status)
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/turbo_controller.rb
class TurboController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => error
        if get?
          raise error
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          p "navigation_location"
          p navigation_location
          redirect_to navigation_location
        end
      end
    end

    self.responder = Responder
    respond_to :html, :turbo_stream
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: %i[ show edit update destroy ]

  # GET /videos or /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1 or /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos or /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to video_url(@video), notice: "Video was successfully created." }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1 or /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to video_url(@video), notice: "Video was successfully updated." }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1 or /videos/1.json
  def destroy
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url, notice: "Video was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def video_params
      params.require(:video).permit(:title, :key_word, :upload_at, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :Keyword %><br>
    <%= form.collection_check_boxes(:keyword_ids, Keyword.order(:word), :id, :word) %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body, size: "70x50"%><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit :class => "hollow button secondary"%>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<%= Article.public_count %> articles in total
<br>
<br>
<% @articles.each do |article| %>
    <% unless article.archived? %>
        <div class="callout">
            <% article.keywords.each do |keyword| %>
                <%= render(ProgressBadgeComponent.new(status: keyword.word)) do %>
                    <% keyword.word %>
                <% end %>
            <% end %>
            <p>
                <%= link_to article.title, article %>
            </p>
        </div>
    <% end %>
<% end %>

<% if current_user && current_user.role == "admin" %>
    <%= link_to "New Article", new_article_path, :class => "hollow button secondary" %>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article%>

app/views/articles/show.html.erb
<div class="callout"><h2><%= @article.title %></h2></div>

<%= RedCloth.new(@article.body).to_html.html_safe %>

<% if current_user && current_user.role == "admin" %>
    <ul>
        <li><%= link_to "Edit", edit_article_path(@article) %></li>
        <li><%= link_to "Delete", article_path(@article), data: {
                        turbo_method: :delete,
                        turbo_confirm: "Are you sure?"
                        } %></li>
    </ul>
<% end %>

<hr>
<h2>Comments</h2>
<%= render @article.comments %>

<hr>
<h2>Add a comment:</h2>
<%= render 'comments/form' %>


<%# @article.comments => [<comment1>, <comment2>, <comment3>]
<comment1>.class == Comment
comment_path => /comments/_comment.html.erb

@articles = [<article1>, <article2>]
<article1>.class == Article

=> views/articles/_article.html.erb
_ => partial

render 'article' => _article.html.erb
render file: 'article' => article.html.erb %>

app/views/comments/_comment.html.erb
<div class="comment-container">
    <div class="comment-element">
        <p>
            <%= fa_icon "user" %>:
            <%= comment.commenter %>
        </p>
        <p>
            <%= fa_icon "comment" %>:
            <%= comment.body %>
        </p>
    </div>
</div>
<% if current_user && current_user.role == "admin" %>
    <p>
        <%= link_to "Destroy Comment", [comment.article, comment], data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
            } %>
    </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <br>
  <p>
    <%= form.submit :class => "hollow button secondary"%>
  </p>
<% end %>

app/views/home/_header.html.erb
<!-- <div
  class="title-bar"
  data-responsive-toggle="example-menu"
  data-hide-for="medium"
>
  <button class="menu-icon" type="button" data-toggle="example-menu"></button>
  <div class="title-bar-title">Menu</div>
</div> -->

<div class="top-bar" id="example-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <%= link_to 'Compsyc', root_path, class:"navbar-brand" %>
      <%= image_tag "logo.png", :width => '50px', :style => 'margin-right: 1em'%>
      <li>
        <button
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span></span>
        </button>
      </li>
      <li class="nav-btn">
        <%= link_to 'Videos', videos_path, class:"nav-link" %>
      </li>
      <li class="nav-btn">
        <%= link_to 'Articles', articles_path, class:"nav-link" %>
      </li>
      <li class="nav-btn">
        <%= link_to 'About', home_about_path, class:"nav-link" %>
      </li>
    </ul>
  </div>
  <div class="top-bar-right">
    <%# registration %>
    <ul class="menu align-right">
      <% if user_signed_in? %>
      <li class="nav-btn">
        <%= link_to 'Sign out', destroy_user_session_path, data:
        {"turbo-method": :delete}, class:"nav-link"%>
      </li>
      <li class="nav-btn">
        <%= link_to 'Edit profile', edit_user_registration_path,
        class:"nav-link" %>
      </li>
      <% else %>
      <li class="nav-btn">
        <%= link_to 'Sign up', new_user_registration_path, class:"nav-link" %>
      </li>
      <li class="nav-btn">
        <%= link_to 'Sign in', new_user_session_path, class:"nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/index.html.erb
<h1>Home</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%= render(ExampleComponent.new(title: "my title!!!")) do %>
  Hello, World!
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%# <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> %>

    <!-- Foundation CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.7.4/dist/css/foundation.min.css" crossorigin="anonymous">

    <link rel="stylesheet" href="../../../assets/stylesheets/application.css" />
    <%# <link href="/assets/favicon.ico" rel="shortcut icon" type="image/x-icon" /> %>

    <title>Compsyc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div style="padding-left: 10em; padding-right: 10em;">
      <br>
      <% if notice %>
        <p><%= notice %></p>
      <% end %>
      <% if alert %>
      <p><%= alert %></p>
      
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/edit.html.erb
<h2>Edit <%= resource_name.to_s.humanize %></h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
    <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
  <% end %>

  <div class="field">
    Select your role
    <br>
    <%= f.select :role, collection: User.roles.keys.to_a %>
  </div>

  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
    <% if @minimum_password_length %>
      <br />
      <em><%= @minimum_password_length %> characters minimum</em>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "current-password" %>
  </div>

  <div class="actions">
    <%= f.submit "Update", :class => "hollow button secondary"%>
  </div>
<% end %>

<h3>Cancel my account</h3>

<p>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, data: {
                turbo_method: :delete,
                turbo_confirm: "Are you sure?"
            } %></p>

<%= link_to "Back", :back %>

app/views/users/new.html.erb
<h2>Sign up</h2>
  <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
    <%= render "devise/shared/error_messages", resource: resource %>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="field">
      Select your role
      <br>
      <%= f.select :role, collection: User.roles.keys.to_a %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "new-password" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
    </div>

    <div class="actions">
      <%= f.submit "Sign up", :class => "hollow button secondary"%>
    </div>
  <% end %>
<%= render "devise/shared/links" %>

app/views/videos/_form.html.erb
<%= form_with(model: video) do |form| %>
  <% if video.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
        <% video.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class:"form-control" %>
  </div>

  <div>
    <%= form.label :key_word, style: "display: block" %>
    <%= form.text_field :key_word, class:"form-control" %>
  </div>

  <div>
    <%= form.label :upload_at, style: "display: block" %>
    <%= form.date_field :upload_at, class:"form-control" %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url, class:"form-control" %>
  </div>

  <br>

  <div>
    <%= form.submit :class => "hollow button secondary"%>
  </div>
<% end %>

app/views/videos/_video.html.erb
<div id="<%= dom_id video %>">
  <% if !(current_user && current_user.role == "admin") %>
    <tr>
      <th scope="row"><%= video.title%></th>
      <td><%= video.key_word%></td>
      <td><%= video.upload_at%></td>
      <td><%= link_to "Youtube Link", video.url%></td>
    </tr>
  <% else %>
    <tr>
      <th scope="row"><%= video.title%></th>
      <td><%= video.key_word%></td>
      <td><%= video.upload_at%></td>
      <td><%= link_to "Youtube Link", video.url%></td>
      <td><%= link_to "Edit", edit_video_path(video) %></td>
      <td><%= link_to "Destroy", video, method: :delete %></td>
    </tr>
  <% end %>
</div>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render "form", video: @video %>

<br>

<div>
  <%= link_to "Back to videos", videos_path %>
</div>

app/views/videos/index.html.erb
<h1>Videos</h1>
<table class="table">
  <thead>
    <% if !(current_user && current_user.role == "admin") %>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Key words</th>
        <th scope="col">Upload at</th>
        <th scope="col">Link</th>
      </tr>
    <% else %>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Key words</th>
        <th scope="col">Upload at</th>
        <th scope="col">Link</th>
        <th scope="col">Edit</th>
        <th scope="col">Destroy</th>
      </tr>
    <% end %>
  </thead>
  <tbody>
    <% @videos.each do |video| %>
      <%= render video %>
    <% end %>
  </tbody>
</table>
<%# <%= debug(current_user) %>
<% if current_user && current_user.role == "admin" %>
  <%= link_to "New video", new_video_path, :class => "hollow button secondary"%>
<% end %>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render "form", video: @video %>

<br>

<div>
  <%= link_to "Back to videos", videos_path %>
</div>

app/views/videos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @video %>

<div>
<%= link_to "Back to videos", videos_path %>
<% if current_user && current_user.role == "admin" %>
  <%= link_to "Edit this video", edit_video_path(@video) %>
  <%= button_to "Destroy this video", @video, method: :delete %>
<% end %>
</div>